<?php

namespace WP\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchUser($search, $tolerance = 3) {
        $query = $this->createQueryBuilder('u')
            ->leftJoin('u.image','i')
            ->addSelect('i')
            ->where('LEVENSHTEIN(u.username, :search) <= :tolerance')
            ->orWhere('u.username LIKE :searchLike')
            ->orderBy('u.username','asc')
            ->setParameter('search', $search)
            ->setParameter('searchLike','%'.$search.'%')
            ->setParameter('tolerance', $tolerance);
        return $query
            ->getQuery()
            ->getResult();
    }

}
