<?php

namespace WP\ExoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * CommentAskingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentAskingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPageCommentByAsking($askingId, $page, $nbPerPage) {
        $query = $this->createQueryBuilder('ca')
            ->leftJoin('ca.user', 'u')
            ->addSelect('u')
            ->leftJoin('ca.asking', 'a')
            ->addSelect('a')
            ->where('a.id = '.$askingId)
            ->orderBy('ca.id','desc')
            ->getQuery();

        $query->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
