<?php

namespace WP\ExoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * SupplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPageSupply($page, $nbPerPage) {
        $query = $this->createQueryBuilder('s')
            ->leftJoin('s.user','u')
            ->addSelect('u')
            ->where('s.isValidate = :val')
            ->orderBy('s.id','desc')
            ->setParameter('val','0')
            ->getQuery();

        $query->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getSearchSupply($search, $tolerance = 3) {
        $query = $this->createQueryBuilder('s')
            ->leftJoin('s.user','u')
            ->addSelect('u')
            ->where('LEVENSHTEIN(s.title, :search) <= :tolerance')
            ->orWhere('s.title LIKE :searchLike')
            ->orderBy('s.id','desc')
            ->setParameter('search', $search)
            ->setParameter('searchLike','%'.$search.'%')
            ->setParameter('tolerance', $tolerance);
        return $query
            ->getQuery()
            ->getResult();
    }

}
